version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "attackbot"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-i0mkvixt2gb1"
s3_prefix = "attackbot"
region = "us-west-2"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
